site_name: 2º DAW - Desarrollo Web en Entorno Servidor - Curso 24/25
site_url: https://jssdocente.github.io/dwes2425
use_directory_urls: false

nav:
  - "Inicio": "index.md"
  - "1.- Arquitecturas Web": "01arquitecturas.md"
  - "2.- El lenguaje PHP":
    - "Introducción": 02_index.md
    - "PHP Básico": 02.1_php_basico.md
    - "PHP Avanzado": 02.2_php_avanzado.md
    - "PHP evolución": 02.3_php_versiones_evolucion.md
  - "3. PHP Orientado a Objetos": "03phpoo.md"
  # - "4.- Programación Web": "04web.md"
  # - "5.- Herramientas Web": "05herramientas.md"
  # - "6.- Acceso a Datos": "06accesoDatos.md"
  # - "7.- Frameworks PHP - Laravel": "07frameworks.md"
  # - "8.- Uso avanzado de Frameworks": "08frameworks2.md"
  # - "8.- Servicios REST": "09rest.md"
  - "Anexo":
    - "Anexo I. Arquitecturas Web": "extra/ArquitecturasWebExtendido.md"

  - "Guias":
    - "Configuración entorno desarrollo PHP con Laravel Herd": "extra/guias/02.config_devenv_laravel_herd.md"

theme:
  language: es
  favicon: imagenes/favicon.png
  name: "material"
  palette:
    - scheme: default
      primary: light blue
      accent: "Teal"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo noche
    - scheme: slate 
      primary: light blue
      accent: "Teal"
      toggle:
        icon: material/toggle-switch
        name: Cambiar a modo día
  icon:
    annotation: material/plus-circle
  font:
    text: Roboto
    code: Roboto Mono
  logo: "imagenes/logofp.png"
  features:
    - header.autohide
    - toc.integrate
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - navigation.top
    - content.code.annotate

extra:
  search:
    language: "es"
  social:
    - icon: material/twitter
      link: https://twitter.com/aitormedrano
    - icon: material/email-edit
      link: mailto:<a.medrano@edu.gva.es>
  #analytics:
    #provider: google
    #property: G-X6D0LR7TC8

plugins:
  - search
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3

copyright: 2024-2025 Jesús García - Licencia CC BY-NC-SA
